import clases

persona = clases.Persona("","",1.86,18)
persona.setNombre("Jose Fernando")
persona.setApellido("Frugone Jaramillo")
persona.setAltura(1.86)
persona.setEdad(50)

print(f"La persona es {persona.getNombres()} {persona.getApellidos()} {str(persona.getAltura())} {str(persona.getEdad())}")

print(persona.hablar())

informatico = clases.Informatico("","",1,86,25,5,"","","",5,"")
informatico.setNombre("Jose Fernando")
informatico.setApellido("Frugone Jaramillo")
informatico.setAltura(1.86)
informatico.setEdad(50)
informatico.setTitulo("Lcdo en Informatica")
informatico.setAestudios(5)
informatico.setCertificado("Prog. de Microcomputadoras")
informatico.setUniversidad("Universidad de Guayaquil")
informatico.setOtros("ESPOL")
informatico.setExperiencia(10)
informatico.setLenguajes("Php,Laravel,Python,Mysql")

print("\n")
print("######### ################### Datos Personales y profesionales ###########\n",end="")
print("\n")
print("Nombres         : " + informatico.getNombres())
print("Apellidos       : " + informatico.getApellidos())
print("Altura          : " + str(informatico.getAltura()))
print("Edad            : " + str(informatico.getEdad()))
print("Titulo          : " + informatico.getTitulo())
print("Años de estudio : " + str(informatico.getAñosEst()))
print("Certificado     : " + informatico.getCertificado())
print("Universidad     : " + informatico.getUniversidad())
print("Otros           : " + informatico.getOtros())
print("Experiencia     : " + str(informatico.getExperiencia()))
print("Lenguajes       : " + informatico.getLenguajes())

tecnico = clases.TecnicoRedes("","",1,74,30,5,"","","",5,"",5,5)

tecnico.setNombre("Juan Fernando")
tecnico.setApellido("Garzon Aviles")
tecnico.setEdad(46)
tecnico.setAltura(1.86)
tecnico.setTitulo("Ing. en Telecom")
tecnico.setAestudios(5)
tecnico.setCertificado("Mantenimiento de PC")
tecnico.setUniversidad("UPS")
tecnico.setOtros("ESPOL")
tecnico.setExperiencia(10)
tecnico.setLenguajes("PHP,Java,Arduino,Ubunto,Python")
tecnico.setExpRedes(10)
tecnico.setAuditar("Experto")

print("\n")
print("############# Datos del Tecnico de Redes ##########\n",end="")
print("\n")
print("Nombres         : " + tecnico.getNombres())
print("Apellidos       : " + tecnico.getApellidos())
print("Altura          : " + str(tecnico.getAltura()))
print("Edad            : " + str(tecnico.getEdad()))
print("Años de estudio : " + str(tecnico.getAñosEst()))
print("Certificado     : " + tecnico.getCertificado())
print("Experiencia     : " + str(tecnico.getExperiencia()))
print("Exp. Redes      : " + str(tecnico.getExpRedes()))
print("Auditar         : " + tecnico.getAuditarRedes())

